name       : gamescope-git
version    : 3.14.3
release    : 1
source     :
    - git|https://github.com/ValveSoftware/gamescope.git : f8c873e35278e68b16080c6ab060be6f5fbd91a7
license    : BSD-2-Clause
component  : system.utils
homepage   : https://github.com/ValveSoftware/gamescope
summary    : gamescope - a micro wayland compositor useful for games
description: |
    gamescope is a micro wayland compositor useful for games. It creates a virtual environment for a game application to run in that helps solves various headaches such as resolution, alt-tabbing, mouse focusing issues etc. Gamescope also tries to remove as many unneccessary copies as it can and should provide better latency.
networking : yes
patterns   :
    - /*
builddeps  :
    - pkgconfig(glm)
    - pkgconfig(libavif)
    - pkgconfig(libcap)
    - pkgconfig(libdecor-0)
    - pkgconfig(libdisplay-info)
    - pkgconfig(libdrm)
    - pkgconfig(libliftoff)
    - pkgconfig(libpipewire-0.3)
    - pkgconfig(openvr)
    - pkgconfig(sdl2)
    # - pkgconfig(stb)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-server)
    # Not currently used, it builds it's own
    - pkgconfig(wlroots)
    - pkgconfig(x11)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xkbcommon)
    - pkgconfig(xmu)
    - pkgconfig(xrender)
    - pkgconfig(xres)
    - pkgconfig(xtst)
    - pkgconfig(xwayland)
    - pkgconfig(xxf86vm)
    - glslang-devel
    - vulkan-headers
setup      : |
    %meson_configure -Dforce_fallback_for="stb" -Dpipewire=enabled
build      : |
    %ninja_build
install    : |
    %ninja_install

    # Unneeded. This were only for libs that were statically compiled in
    rm -v $installdir/usr/include/vkroots.h \
          $installdir/usr/lib64/pkgconfig/vkroots.pc
    rm -rfv $installdir/usr/include/wlr \
            $installdir/usr/lib64/libwlroots.a \
            $installdir/usr/lib64/pkgconfig/wlroots.pc
    find $installdir -type d -empty -print -delete
