name       : ludusavi
version    : 0.25.0
release    : 1
source     :
    - https://github.com/mtkennerly/ludusavi/archive/refs/tags/v0.25.0.tar.gz : 26fbbed72a8314fa3c25b3cd4434988952c78cd21e22fb0dd041ca1a9cfed988
homepage   : https://github.com/mtkennerly/ludusavi
license    : MIT
component  : system.utils
summary    : Backup tool for PC game saves
description: |
    Backup tool for PC game saves
networking : yes
builddeps  :
    - rust
setup      : |
    cargo fetch --locked
build      : |
    cargo build --frozen --release \
                --all-features
install    : |
    install -Dm00755 target/release/ludusavi -t $installdir/usr/bin/
    install -Dm644 assets/com.github.mtkennerly.ludusavi.metainfo.xml -t $installdir/usr/share/metainfo/
    install -Dm644 assets/icon.png $installdir/usr/share/icons/hicolor/64x64/apps/ludusavi.png
    install -Dm644 assets/icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/ludusavi.svg
    install -Dm644 assets/ludusavi.desktop -t $installdir/usr/share/applications/
