name       : vesktop
version    : 1.5.2
release    : 1
source     :
    - https://github.com/Vencord/Vesktop/releases/download/v1.5.2/vesktop-1.5.2.tar.gz : a49595d362fa21b0f4525fc25d4484d1ee494a6f3fbedbc06f8c29cb400367db
license    : Distributable
component  : network.im
homepage   : https://github.com/Vencord/Vesktop
summary    : All-in-one voice and text chat for gamers
description: |
    All-in-one voice and text chat for gamers that's free, secure, and works on both your desktop and phone.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xshmfence)
rundeps    :
    - llvm
    - libayatana-appindicator
    - opus
# strip and debug will prevent krisp noise supression from loading
strip      : no
debug      : no
install    : |
    install -Dm00644 $pkgfiles/vesktop.desktop $installdir/usr/share/applications/vesktop.desktop
    install -Dm00644 $pkgfiles/vesktop.png $installdir/usr/share/icons/hicolor/512x512/apps/vesktop.png

    # Binary
    install -dm00755 $installdir/usr/share/vesktop
    cp -Ra * $installdir/usr/share/vesktop/
    install -Dm00755 $pkgfiles/vesktop.sh $installdir/usr/bin/vesktop
