name       : ryujinx
version    : 1.1.1281
release    : 1
source     :
    - https://github.com/Ryujinx/Ryujinx/archive/refs/tags/1.1.1281.tar.gz : f2b43228d2d59df523c29760aba42e9b6553be477e27899b0eb85b0cd6b8173a
license    : MIT
component  : games.emulator
homepage   : https://github.com/Ryujinx/Ryujinx
summary    : Experimental Nintendo Switch Emulator written in C#
description: |
    Experimental Nintendo Switch Emulator written in C#
# Strip/debug no are required for self-contained dotnet
strip      : no
debug      : no
networking : yes
builddeps  :
    - pkgconfig(gtk+-3.0)
    - alsa-lib
    - dotnet-sdk
    - pulseaudio
    - jack-audio-connection-kit
setup      : |
    %patch -p1 -i $pkgfiles/0001-Revert-nuget-bump-Microsoft.CodeAnalysis.CSharp-from.patch
    dotnet nuget locals all -c
build      : |
    # Avalonia build has HiDPI issues
    dotnet publish -c Release \
                   -r linux-x64 \
                   --nologo \
                   --self-contained true \
                   -p:DebugType=none \
                   -p:ExtraDefineConstants=DISABLE_UPDATER \
                   -p:Version=$version \
                   -o publish_gtk src/Ryujinx.Gtk3
install    : |
    install -dm755 $installdir/usr/share/ryujinx
    cp -ra publish_gtk/* "$installdir/usr/share/ryujinx/"

    # Use gtk3 UI by default
    mv $installdir/usr/share/ryujinx/Ryujinx.Gtk3 $installdir/usr/share/ryujinx/Ryujinx

    # symlinks
    install -dm755 "$installdir/usr/bin"
    ln -s "../share/ryujinx/Ryujinx.sh" $installdir/usr/bin/ryujinx

    # .desktop
    install -Dm644 $pkgfiles/Ryujinx.desktop $installdir/usr/share/applications/Ryujinx.desktop
    # icon
    install -Dm644 distribution/misc/Logo.svg $installdir/usr/share/icons/hicolor/scalable/apps/Ryujinx.svg
    # mimetype
    install -Dm644 distribution/linux/mime/Ryujinx.xml "$installdir/usr/share/mime/packages/Ryujinx.xml"
